apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - serviceaccount.yml
  - storageclass.yml

images:
  - name: wayfinder
    newName: 682761213103.dkr.ecr.ap-southeast-2.amazonaws.com/wayfinder
    newTag: dev

patches:
  - target:
      kind: (Deployment|StatefulSet)
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: specialist
  - target:
      kind: StatefulSet
      name: tools
    patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: ebs-auto
