apiVersion: v1
kind: ConfigMap
metadata:
  name: wayfinder-config
  namespace: wayfinder
data:
  REGION: ap-southeast-2
  AWS_DEFAULT_REGION: ap-southeast-2
  MCP_HOST: tools
  MCP_PORT: "8000"
  A2A_HOST: "0.0.0.0"
