apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - secret.yml

images:
  - name: wayfinder
    newTag: dev

patches:
  - target:
      kind: (Deployment|StatefulSet)
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: bedrock-creds
  - path: nodeports.yml
